### ISSUE TITLE
Create symbol for Euclidean space

### ISSUE THREAD

**Issue by anermina** [plurimath/plurimath#214]
There is no symbol for Euclidean space available in Latexmath or Asciimath. Is it possible to create a notation that could generate the Latin capital letter "E" presented with a double-struck typeface?

![image](https://github.com/plurimath/plurimath/assets/55683568/650b3483-e700-4a0b-9bfe-54b51cbb94b5)

**Comment by ronaldtse** [comment]
@anermina is there any syntax for this symbol in latex?

**Comment by anermina** [comment]
@ronaldtse this symbol can be generated using `\mathbb{E}` or `\Bbb{E}` in Latex, but this is a rather general syntax for double-struck symbols. There is no syntax for this symbol specifically, up to my knowledge.

Mathjax demo generates the above-mentioned symbols like this:
![image](https://github.com/plurimath/plurimath/assets/55683568/c30c909f-93e4-4694-9618-8ecd9f9a4252)

while Plurimath generates them like this (maybe this is also acceptable):
![image](https://github.com/plurimath/plurimath/assets/55683568/d082075a-e5a6-4dd1-8e3d-9e0f4193b9ae)

**Comment by ronaldtse** [comment]
I believe Unicode does have the math symbol for double struck, so we do need to support this math concept.

**Comment by anermina** [comment]
Unicode does have it.

https://www.compart.com/en/unicode/U+1D53C

**Comment by suleman-uzair** [comment]
@anermina , @ronaldtse 

It seems like the issue is just with how the Math is shown on different web browsers. The equation looks right in **Firefox** but not in **Google Chrome**.
We’re using **MathML** without using **MathJax** Library to show the math in [plurimath.org](http://plurimath.org/), and it seems like **Google Chrome** doesn’t fully support it yet.
We use either **MathJax** or another library in [plurimath.org](http://plurimath.org/), to show the Math so it looks the same in all browsers.

1. **Google Chrome**
![Screenshot from 2024-02-15 13-22-33](https://github.com/plurimath/plurimath/assets/96812483/afd3a9d5-d705-4a4a-8ea3-104ec280f052)

2. **FireFox**
![Screenshot from 2024-02-15 13-27-12](https://github.com/plurimath/plurimath/assets/96812483/eb8d46a6-cf6e-423a-af8c-941867b748e5)

3. **MathJax**
![Screenshot from 2024-02-15 12-38-57](https://github.com/plurimath/plurimath/assets/96812483/54f85445-fb25-44bb-b0dd-97d3d345cebb)

**Comment by opoudjis** [comment]
Btw, the Asciimath for doublestruck E is: `bbb(E)`.

**Comment by anermina** [comment]
Thank you @suleman-uzair and @opoudjis ! Closing this ticket.
