### ISSUE TITLE
Enable using backwards epsilon in AsciiMath (`\backepsilon` in LaTeX math)

### ISSUE THREAD

**Issue by anermina** [plurimath/plurimath#217]
`\backepsilon` symbol (϶, "such that" in math) is not available in AsciiMath. Is it possible to create a notation for it, to avoid using `latexmath` blocks just because of this symbol?

**Comment by opoudjis** [comment]
General approach I think we should be taking to adding symbols to AsciiMath:

* Survey the major implementations of AsciiMath, to see if they've already got it: asciidoctor/asciimath, MathJax, and whatever else is out there and actively maintained
* If none of the major implementations have it, add, with preference given to LatexMath as a source of terms
* As a courtesy, I believe we should be suggesting any such new symbols to asciidoctor/asciimath as well

**Comment by ronaldtse** [comment]
The official AsciiMath implementation is ASCIIMath.js, where we could potentially ping. But this looks like to be an overhead in procedure.

**Comment by ronaldtse** [comment]
So this symbol is finally needed here: https://github.com/geolexica/isotc211-glossary/pull/47

Which is the same formula but now published in so many places.

**Comment by ronaldtse** [comment]
@suleman-uzair we ought to have a "table of symbols" shown on the website so people know how to refer to them?

We have "Functions" (https://www.plurimath.org/functions/) but not a section for "Symbols". And all symbols must be referable from all math languages? We should show the rendering of each symbol as well, maybe as a one page table?

**Comment by ronaldtse** [comment]
Actually we did have that task:
* https://github.com/plurimath/plurimath.github.io/issues/6

**Comment by ronaldtse** [comment]
@suleman-uzair do we need to establish simple classes for every Symbol, or have them defined in some YAML file, so we ensure that every symbol is accessible from every math language?

For the "non-official symbols" we can even use some wrapper such as `___{xxx}`.

Instead of having these files:
* https://github.com/plurimath/plurimath/blob/main/Latex-Supported-Data.adoc
* https://github.com/plurimath/plurimath/blob/main/AsciiMath-Supported-Data.adoc
* https://github.com/plurimath/plurimath/blob/main/MathML-Supported-Data.adoc

I'd rather they are in a single YAML file or generated from a Ruby call to list out classes.

**Comment by suleman-uzair** [comment]
@ronaldtse 

1. We have already defined the supported symbols in a Constants file in the directory of each Math language(for example [here’s AsciiMath’s cosntants file](https://github.com/plurimath/plurimath/blob/main/lib/plurimath/asciimath/constants.rb)).
2. The support of **LaTeX** symbols is a one way support, The **LaTeX** symbols are supported for output in the **AsciiMath** only in a case where it’s not supported in the **AsciiMath**.
3. We could use a wrapper(I suggest `${xxx}`) and we can also parse the symbols without the need of a wrapper.
a. If we introduce a wrapper for unofficial symbols in **AsciiMath**, we would need to update the parsing rules accordingly.
b. Supporting **LaTeX** symbols in **AsciiMath** directly, without using a wrapper, would involve combining the symbols from both languages, which should require minimal adjustments.

**Comment by ronaldtse** [comment]
Thanks @suleman-uzair .

1. But I’m thinking that we can reverse the logic to be “symbol-centric” so that we have the symbols in files and then mapping to the math languages. This means when we add a symbol, we have one place to change instead of 5. 
2. Indeed, I wonder if an explicit approach or an implicit approach works better. 
3. Probably easier to directly support without a wrapper if it’s not necessary. It’s only when there are conflicts, but logically I don’t think there’s an issue because symbols always should be matched longest-string-first. The challenge is when a keyword or part of a keyword is reused, and they mean different things, what we can do. That’s why the approach in 1 will expose exactly those problems.

**Comment by suleman-uzair** [comment]
@ronaldtse 
> But I’m thinking that we can reverse the logic to be “symbol-centric” so that we have the symbols in files and then mapping to the math languages. This means when we add a symbol, we have one place to change instead of 5.

We already have symbols in separate files, can you please explain this?
> The challenge is when a keyword or part of a keyword is reused, and they mean different things, what we can do.

Yes, you are right there, the wrapper will be a better option for supporting **LaTeX** symbols in **AsciiMath**. Should we use `___{xxx}` syntax for the wrapper.

**Comment by suleman-uzair** [comment]
Ping @ronaldtse

**Comment by ronaldtse** [comment]
1. Right now we have:
```ruby
module Plurimath
  class Latex
    class Constants
      UNICODE_SYMBOLS = {
        #...
        backepsilon: "&#x3f6;",
        #...
```

The proposal is:

```ruby
module Plurimath
  class Symbols
    class BackEpsilon
      unicode "&#x3f6;"
      latex "backepsilon"
      asciimath "..."
      unicode_math "..."
      
# ...
```

**Comment by suleman-uzair** [comment]
@ronaldtse The proposal will be help in effectively handling conversion of **Formula** to strings. However, for parsing(input to tree) and transformation (tree to **Formula**), constant files will still be required.
For example, in [AsciiMath parsing rules](https://github.com/plurimath/plurimath/blob/5329e26dcb7582e65a98a802995ef1d33b4fae60/lib/plurimath/asciimath/parse.rb#L32) and [LaTeX transformation rules](https://github.com/plurimath/plurimath/blob/5329e26dcb7582e65a98a802995ef1d33b4fae60/lib/plurimath/latex/transform.rb#L831).
Since not all classes, symbols, or parenthesis  are universally supported across languages, we’ll need to create classes as proposed and maintain the associated constants in the constants files.

**Comment by ronaldtse** [comment]
@suleman-uzair
> Since not all classes, symbols, or parenthesis are universally supported across languages

The point is we need ALL classes and symbols (perhaps also parentheses) to be supported across ALL languages.

The goal is plurimath is to support transforming from one language to another. We cannot afford to have certain symbols that cannot be transformed.

**Comment by suleman-uzair** [comment]
> The point is we need ALL classes and symbols (perhaps also parentheses) to be supported across ALL languages.
> 
> The goal is plurimath is to support transforming from one language to another. We cannot afford to have certain symbols that cannot be transformed.

@ronaldtse I’m working on adding files for symbols as discussed. But as for supporting all classes(**sin**, **mod**, **sum**, etc...), we need changes in parsing, and we will have to add parsing rules for the un-supported classes.

Syntax-related issues like **multiscript** is not supported in **LaTeX** and **AsciiMath**, and there is no valid syntax mentioned in the relative grammars either, For example,
**UnicodeMath** and **MathML** support **multiscripts**, following is **UnicodeMath** syntax.
`_𝑛^𝑘 C_𝑘^𝑛`
However, it’s not supported in **LaTeX** and **AsciiMath**, so the syntax of these types of classes will have to be defined in **Plurimath** for all other math presentations.

do we need to get all of the classes(**coprod**, **multiscript**, **phantom**, etc...) to be supported in ALL languages or do we only need to support symbols?
if we need to support all the classes, then I suggest we should have a separate ticket for that.

**Comment by suleman-uzair** [comment]
@ronaldtse 

![Screenshot 2024-05-02 at 12 40 32 PM](https://github.com/plurimath/plurimath/assets/96812483/b0ff8590-2111-4f77-8852-3588ffa0f403)
Supporting **ALL symbols** in **ALL LANGUAGES** without a wrapper is causing equations to be parsed incorrectly(as you already mentioned above).
As an example,
previously parsed equation: `sum_(i = 1)^n i^(3)`
parsing equation now: `sum_(i = 1)^(ni) ^ 3`
We should add the wrapper with symbol classes.

**Comment by suleman-uzair** [comment]
@ronaldtse ping

**Comment by opoudjis** [comment]
In the recent https://github.com/plurimath/plurimath/pull/252/files#diff-1e668f4ae4bf8d65de0634f02fce10cdb381c775e9d62d8e37d74ab300d74f8e lib/plurimath/math/symbols/ge.rb

````
def to_asciimath
          parsing_wrapper("ge")
        end
````

has been changed to

````
  def to_asciimath
          "ge"
        end
````

because it was breaking a test in isodoc.

I of course am having trouble following what is happening here, and if I have misunderstood what is going on here, I apologise in advance. But as a consumer of Plurimath, I'll make these observations:

* Plurimath is the Metanorma maths engine, and it needs to do what it needs to do to fulfil @ronaldtse ’s  grand statement

> The point is we need ALL classes and symbols (perhaps also parentheses) to be supported across ALL languages.

* ... Right up until export. Because anything that outputs MathML that does not comply to the W3C standard for MathML (or, more to the point, the MathJax realisation of it) is unfit for use.
* The same though applies to AsciiMath and LatexMath. You cannot presuppose that any Asciimath exported by Plurimath will only be consumed by Plurimath downstream. It is meant to be available for use with preexisting Asciimath consumers.
* In Metanorma Presentation XML, in particular, we use MathML as the base exchange format and target format, and we indeed parse Asciimath in input into MathML, if none was supplied. But we also export AsciiMath as a fallback. The reason we do that is (a) to have something more easily human-readable, for human debugging; (b) as a fallback in case something goes wrong with the MathML.
* The use case for this may not have been well thought through (it arose, from memory, when we were dealing with a huge NIST document full of MathML, and wanted to help our own editors). But the point is, that AsciiMath can be used with general AsciiMath processors, rather than Plurimath. Indeed, it is expected to be.
* You addressed the issue I raised for my isodoc test, "why is `ge` being rendered as `__{ge}` in Asciimath, by disabling the wrapper in that one instance. But we can't have a one-instance solution. You are using the wrapper elsewhere, and you are adopting it as the means to import new symbols like backepsilon.

I don't know why `ge` was wrapped, but if the goal to "support all symbols in all languages" is going to result in Asciimath that asciimath.js doesn't understand, then something has to give.

* `ge` is the correct Asciimath for `>=`
* `backepsilon` is not in Asciimath
* `_{backepsilon}` is, I take it, a fallback: a way for non-Plurimath processors to degrade gracefully if they encounter `backepsilon`
* But Asciimath processors outside of Plurimath should not expected to make sense of `_{ge}` when `ge` is supported
* And I don't see https://asciimath.org/ doing a great job of dealing with `a __{backepsilon} b` either
* If `ge` was wrapped in error on Asciimath export (to_asciimath), then we need to ensure there are no other such errors before release.
* If `ge` was wrapped deliberately, as some sort of internal consistency, then there needs to be some sort configuration to disable that wrapping *by default*, and only enable it when we know the output will be consumed only by Plurimath
* And any wrapping that will end up consumed by the outside world needs to actually work in the outside world. By all means wrap backepsilon, but not as `__{backepsilon}`:


![Screenshot 2024-06-01 at 22 41 46](https://github.com/plurimath/plurimath/assets/1911039/ea3fa3fd-5b4f-4410-b541-915efdd116bf)

I think we're needing to end up with two realisations of the wrapper: a Plurimath-only realisation that is unambiguous for all symbols can keep going, but  `__{ge}` and `__{backepsilon}` cannot be used for AsciiMath that will be consumed outside of Plurimath. The assumption that we are operating in a Plurimath-only ecosystem, and so are our users, is simply incorrect. Whatever we do for an unambiguous, Plurimath-only export,

* I expect `>=` to export by default to `ge`. We are meant to be exporting Asciimath, not Ribose-Proprietary-Asciimath. MathJax and AsciiMathML don't support Ribose-Proprietary-Asciimath.
* I expect backepsilon to export to something that will not result in the aforegoing nonsense on asciimath.org, *even if it breaks round-tripping*. The goal of (1) round-tripping and (2) universality is unachievable, and (1) MUST BREAK at the expense of (2) outside of a Plurimath-only realisation.
* The only safe way of wrapping backepsilon in Asciimath outside of Plurimath is `" backepsilon "`. With the spaces.
* And indeed, each output format we support is going to have its own non-roundtrippable wrapper for stuff it doesn't understand. `_{}` looks like a LaTeX only wrapper. In MathML it would be `<mtext>` or `<mo>`. In UnicodeMath, who knows, I don't know why we're supporting it to begin with. In OOXML, no idea either, but I would not be unleashing `_{backepsilon}` on OOXML.

**Comment by ronaldtse** [comment]
> The only safe way of wrapping backepsilon in Asciimath outside of Plurimath is " backepsilon ". With the spaces.
> each output format we support is going to have its own non-roundtrippable wrapper for stuff it doesn't understand.

I agree. The wrapper for a particular math syntax  should be (if possible) backwards compatible with the original (unextended) syntax.

**Comment by ronaldtse** [comment]
Further to what @opoudjis mentioned, if we have a round-trip-able wrapper, that’s even better.

**Comment by ronaldtse** [comment]
For the backwards compatible wrapper for AsciiMath, we could use something like `”{backepsilon}”`?

**Comment by opoudjis** [comment]
I was thinking `" PLURIMATH:_{backepsilon} "`, which is uglier, but guaranteed to be unambiguous. But ` "{backepsilon}" ` or  ` "_{backepsilon}" `  would be unambiguous enough.

**Comment by ronaldtse** [comment]
Maybe we can use the `P` to indicate it is a Plurimath extension?
* AsciiMath wrapper: `"P{backepsilon}"`
* LaTeX wrapper: `\text{P[some symbol name]}`
* UnicodeMath wrapper: `"P{backepsilon}"`
* What else?
