### ISSUE TITLE
Implement automatic testing against some Metanorma math samples

### ISSUE THREAD

**Issue by ronaldtse** [plurimath/plurimath#249]
If this is about seeing if it blows up any Metanorma documents, then the testing needs to be between you and @CAMOBAP. I have little idea how Github Actions works for this kind of testing, and I don't have the spare time to work it out.

* @CAMOBAP Please run metanorma-cli on Github Actions with a Gemfile.devel pointing to this branch of plurimath. @CAMOBAP I don't know if you got Gemfile.devel working on metanorma-cli. Please do so if you haven't already, and do a run with this branch, so we can confirm that it does not introduce any new crashes.
* Please show @suleman-uzair how to do so himself in future, because as an infrastructure gem, he will need to run sanity checks on plurimath rather than me finding out on release about plurimath bugs. This has happened a couple of times already. What is involved @suleman-uzair is you pushing a PR to metanorma-cli, with a Gemfile.devel file at top level looking like this:

````
gem "plurimath", git: "https://github.com/plurimath/plurimath", branch: "whatever"
````

But like I said, I have no idea if this is working for metanorma-cli yet; I know we tried to get it working, but I don't remember if we succeeded.

That aside, find a Metanorma document with backepsilon in it, and compile it.

_Originally posted by @opoudjis in https://github.com/plurimath/plurimath/issues/244#issuecomment-2116473876_

**Comment by CAMOBAP** [comment]
Gemfile.devel works, I have tested metanorma-cli with plurimath from git on metanorma's side https://github.com/metanorma/metanorma-cli/actions/runs/9162773624/job/25192046040 

@ronaldtse @opoudjis please confirm:
1. We should do testing on plurimath side, right?
2. Which repos should be tested?

**Comment by opoudjis** [comment]
I am assuming that the workflow is as follows:

* Plurimath is already testing on a PR in GHA, so nothing new needs to be done for that.
* We test metanorma-cli with the new Plurimath branch as Gemfile.devel; if you've already done that, then the requirement is satisfied—and @suleman-uzair we have found bugs that way: see the Github Action log for sample-bipm
* We only need metanorma-cli as a repo to test again, since (in my opinion) that has a good enough range of math to test Plurimath against.

As long as Suleman knows how to initiate such tests in future for metanorma-cli, we're now good. Thank you @CAMOBAP!

And @suleman-uzair we now have formulas that trigger errors, in BIPM.

````
ii(L)_{ii(lambda)} (ii(T)_{90}) = c_1 / {n_{ii(lambda)}^2 ii(lambda)^5} [exp(c_2 / {n_{ii(lambda)} ii(lambda) ii(T)_{90}}) - 1]^{-1} 
````

````
{ii(L)_{ii(lambda)} (ii(T)_{90})}/{ii(L)_{ii(lambda)} (ii(T)_{90} (ii(X)))} = {exp(c_2 / {ii(lambda) ii(T)_{90} (ii(X))}) - 1} / {exp (c_2 / {ii(lambda) ii(T)_{90}}) - 1} ,
````

I am worried by the comma in the second instance; the source text is sources/guide-its90/guide-its90-06.adoc:

````
Above the freezing point of silver, stem:[1234.93 "unitsml(K)"] (stem:[961.78 "unitsml(degC)"]), the temperature stem:[ii(T)_{90}] is, according to the definition of the ITS-90, defined by the equation

[[eq1]]
[stem]
++++
{ii(L)_{ii(lambda)} (ii(T)_{90})}/{ii(L)_{ii(lambda)} (ii(T)_{90} (ii(X)))} = {exp(c_2 / {ii(lambda) ii(T)_{90} (ii(X))}) - 1} / {exp (c_2 / {ii(lambda) ii(T)_{90}}) - 1} ,
++++

where stem:[ii(T)_{90} (ii(X))] refers to the silver stem:[{ii(T)_{90}("Ag") = 1234.93 "unitsml(K)"}],  ....
````

.... Unfortunately, and I'm really annoyed to say this, we do have to deal with trailing commas like this, even though they are extraneous to the formula.

There may be others in subsequent documents in the repo; you will need to launch this test again after you've addressed this bug—or, if you want to be proactive, you can download the samples repository involved,  https://github.com/metanorma/mn-samples-bipm, and run bundle exec metanorma site generate with Gemfile pointing to your plurimath branch, since that's the only repo that failed. But to be safe, I suggest you just rerun on GHA.

**Comment by opoudjis** [comment]
Oh, I understand what you meant @CAMOBAP : should an PR to Plurimath trigger a test run of metanorma-cli with that PR in GHA?

... It... seems to me to be overkill. But if you can set up a job that @suleman-uzair can manually trigger, and if it can retrieve the PR's branch name and inject a Gemfile.devel alluding to it automatically... it would be useful. Because of how expensive these jobs are though, I'd want it to be a manual trigger, not automatic.

**Comment by opoudjis** [comment]
Also @CAMOBAP this is the first time that BSI has run successfully on all platforms in GHA for metanorma-cli. Thank you for fixing that!

**Comment by CAMOBAP** [comment]
@opoudjis @suleman-uzair just to be on the same page, testing with dev branch on `metanorma-cli` side is not automated right now.

@suleman-uzair once you need to test plurimath simply create draft PR in `metanorma-cli` with `Gemfile.devel`:

```ruby
gem 'plurimath', github: 'plurimath/plurimath', branch: 'updates/symbols_support'
```

Here is example of PR: https://github.com/metanorma/metanorma-cli/pull/329. It's not for merge, just for test.

**UPD**. I may also update the workflow that will accept `Gemfile.devel` from UI, this is how it will looks like:

<img width="359" alt="Screenshot 2024-05-21 at 11 12 58 AM" src="https://github.com/plurimath/plurimath/assets/2169738/9a356e7e-ba19-475a-9e07-7438c91f4694">

This will help us avoid test PRs pollution on metanorma-cli side

@opoudjis @suleman-uzair @ronaldtse any thoughts on accepting Gemfile.devel for manual ci run?

**Comment by suleman-uzair** [comment]
@CAMOBAP 
**Gemfile.devel** from UI is a good idea. Right now, I think we can just add a single line here (correct me if I am wrong ?)
This text field ignores new-line which might crash(unless handled) in multiple gem’s testing.
![Screenshot 2024-05-21 at 3 45 19 PM](https://github.com/plurimath/plurimath/assets/96812483/9dfa1916-9802-4b79-aada-64566e3e81ee)
For testing a single gem like **Plurimath** (one line will also work for sure).
Suggestion: If we are looking forward to including other gems for testing in the future, I think we can also take the URL of Gemfile.devel as input and replace it if it already exists in the repo branch?

**Comment by CAMOBAP** [comment]
> Gemfile.devel from UI is a good idea. Right now, I think we can just add a single line here (correct me if I am wrong ?)

For now it's not implemented at all. The screenshot above is from release workflows (not a test one)

> I think we can also take the URL of Gemfile.devel as input and replace it if it already exists in the repo branch?

Which repo branch do you mean?

**Comment by suleman-uzair** [comment]
> Which repo branch do you mean?

@CAMOBAP I meant the **metanorma-cli** branch on which we will be testing **Plurimath**(or other gems at that time).

**Comment by suleman-uzair** [comment]
@CAMOBAP I think it's good enough for now. Let’s go with it.

Thank you.

**Comment by CAMOBAP** [comment]
So I suppose no automation tests are required in the scope of this task, the test suite can be triggered on demand, feel free to reopen
